/* autogenerated by Processing revision 1293 on 2024-11-25 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class RisikoMap extends PApplet {

PImage mappa; // Variabile per l'immagine della mappa
int territorioColor = color(255, 0, 0); // Colore iniziale per un territorio

public void setup() {
  /* size commented out by preprocessor */; // Dimensioni della finestra
  mappa = loadImage("Mappa_Risiko.jpg"); // Carica l'immagine della mappa
}

public void draw() {
  background(255); // Imposta uno sfondo bianco
  image(mappa, 0, 0, width, height); // Disegna la mappa a dimensioni adattate alla finestra
  
  // Esempio di un "territorio" come cerchio per testare l'interattività
  fill(territorioColor); // Colore del territorio
  noStroke(); // Nessun bordo
  ellipse(300, 400, 100, 100); // Disegna un cerchio in una posizione della mappa
}

public void mousePressed() {
  // Controlliamo se il mouse è stato cliccato sopra il territorio
  float distance = dist(mouseX, mouseY, 300, 400);
  if (distance < 50) { // Se il click è dentro il cerchio (raggio 50)
    territorioColor = color(random(255), random(255), random(255)); // Cambia colore a caso
  }
}


  public void settings() { size(1024, 768); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "RisikoMap" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
